// This interface defines the structure of a Client object.
// In other words, it reflects exactly what a client entry
// looks like in the PostgreSQL database. (One of the entries that
// gets returned from "SELECT * FROM clients").

export interface Client {
  // id is a number automatically generated by PostgreSQL (serial primary key)
  id: number;

  // name is a VARCHAR in SQL; its equivalent in typescript is a string
  name: string;

  // email is a VARCHAR in SQL; its equivalent in typescript is a string
  email: string;

  // phone is optional (that's why there is a question mark at the end)
  phone?: string;
}
