version: '3.8'
services:
  backend:
    build: ./backend
    container_name: mediahub_backend
    ports:
      - '4000:4000'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
      - postgres

  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

  postgres:
    image: postgres:15
    env_file:
      - ./backend/.env
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  mongodata:
  pgdata:
