version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"                     # Maps container's port 3000 to host
    environment:
      - PG_USERNAME=${PG_USERNAME}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
      - PG_HOST=db
      - PORT=3000
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"                     # React dev server port
    stdin_open: true                   # Keeps container open for hot reload
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true       # Ensures live reload works inside Docker
    command: ["npm", "run", "dev"]     # If you're using Vite; otherwise use: "npm start"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
